# Generated by Django 4.1.5 on 2024-07-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-created"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
