# Generated by Django 4.1.5 on 2024-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ["-created"],
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
